name: LinkGrabber

on:
  schedule:
    - cron: '0 */1 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Grab Link

        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "0d46k5mdl9fjJksoeeBdwj48d9384ckN0akskssxn2dd93djxkckKs0dfDbsj9s0fvkffshbd5dsh6mv."
          git push
